include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
  errors:
    invalid_use_of_protected_member: error
    missing_required_param: error

linter:
  rules:
    avoid_print: true
    cancel_subscriptions: true
    close_sinks: true
    directives_ordering: true
    prefer_final_locals: true
    use_build_context_synchronously: true
