package com.usman.notepad;

import android.Manifest;
import android.app.Activity;
import android.app.AlertDialog;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.graphics.Bitmap;
import android.os.Build;
import android.os.Bundle;
import android.os.Handler;
import android.provider.MediaStore;
import android.speech.RecognizerIntent;
import android.text.Editable;
import android.text.TextWatcher;
import android.view.Gravity;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;
import com.usman.notepad.data.NoteRepository;
import com.usman.notepad.model.Note;
import com.usman.notepad.security.AppLock;
import com.usman.notepad.security.CryptoManager;
import com.usman.notepad.util.CommandEngine;
import com.usman.notepad.util.SmartTools;
import com.usman.notepad.util.WikiLinkParser;
import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStream;
import java.nio.charset.StandardCharsets;
import java.text.DateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import java.util.List;

public class EditorActivity extends Activity {
    private static final int VOICE=101, IMAGE=102, CAMERA=103, EXPORT_NOTE=104, DEVICE_UNLOCK=105;
    private NoteRepository repo; private Note note; private EditText title,body;private TextView state;private final Handler handler=new Handler();private Runnable pending;private boolean unlocked=false,loading=true,focus=false,commandOpen=false;
    @Override protected void onCreate(Bundle b){super.onCreate(b);repo=new NoteRepository(this);long id=getIntent().getLongExtra("note_id",-1);note=id>0?repo.find(id):new Note();if(note==null)note=new Note();if(note.unlockAt>System.currentTimeMillis()){new AlertDialog.Builder(this).setTitle("Time Capsule").setMessage("This note unlocks "+DateFormat.getDateTimeInstance().format(new Date(note.unlockAt))).setPositiveButton("OK",(d,w)->finish()).setOnCancelListener(d->finish()).show();return;}if(note.locked){showUnlockChoice();return;}unlocked=true;buildUi();}
    private void showUnlockChoice(){new AlertDialog.Builder(this).setTitle("Protected note").setItems(new String[]{"Unlock with app PIN","Use device credential / biometric"},(d,w)->{if(w==0){if(!AppLock.hasPin(this)){Toast.makeText(this,"No app PIN is configured",Toast.LENGTH_LONG).show();finish();return;}AppLock.promptPin(this,"Unlock note",this::decryptAndBuild);}else AppLock.requestDeviceCredential(this,DEVICE_UNLOCK);}).setNegativeButton("Cancel",(d,w)->finish()).setOnCancelListener(d->finish()).show();}
    private void decryptAndBuild(){try{note.body=CryptoManager.decrypt(note.body);unlocked=true;buildUi();}catch(Exception e){Toast.makeText(this,"Unable to decrypt note",Toast.LENGTH_LONG).show();finish();}}
    private void buildUi(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(14),dp(10),dp(14),dp(10));LinearLayout bar=new LinearLayout(this);Button more=new Button(this);more.setText("⋮ Tools");Button saveNow=new Button(this);saveNow.setText("Save");state=new TextView(this);state.setGravity(Gravity.CENTER_VERTICAL);state.setText("Saved");bar.addView(more,new LinearLayout.LayoutParams(0,-2,1));bar.addView(state,new LinearLayout.LayoutParams(0,-2,1));bar.addView(saveNow,new LinearLayout.LayoutParams(0,-2,1));root.addView(bar);title=new EditText(this);title.setHint("Title");title.setTextSize(22);title.setSingleLine(true);root.addView(title);body=new EditText(this);body.setHint("Write your note… Type / to open commands");body.setGravity(Gravity.TOP|Gravity.START);body.setTextSize(17);body.setMinLines(14);ScrollView scroll=new ScrollView(this);scroll.addView(body,new ScrollView.LayoutParams(-1,-2));root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);applyTheme();title.setText(note.title);body.setText(note.body);loading=false;TextWatcher w=new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int before,int count){if(!loading)scheduleSave();}public void afterTextChanged(Editable e){if(!loading&&e==body.getText())maybeSlashCommand();}};title.addTextChangedListener(w);body.addTextChangedListener(w);more.setOnClickListener(v->tools());saveNow.setOnClickListener(v->save(true));}
    private void scheduleSave(){state.setText("Saving…");if(pending!=null)handler.removeCallbacks(pending);pending=()->save(false);handler.postDelayed(pending,700);}
    private void save(boolean snapshot){if(title==null)return;note.title=title.getText().toString();String plain=body.getText().toString();note.body=plain;try{if(note.locked&&unlocked)note.body=CryptoManager.encrypt(plain);}catch(Exception e){Toast.makeText(this,"Encryption failed; note not saved",Toast.LENGTH_LONG).show();return;}repo.save(note,snapshot);repo.setLinkRows(note.id,WikiLinkParser.parse(plain));state.setText("Saved");}
    private void tools(){String[] items={"Mode / template","Slash command","Quick summary","Action items","Related notes","History","Tags","Folder","Reminder","Time capsule","Expiry","Lock / unlock","Theme","Focus mode","Voice to text","Attach image","Camera photo","Attachments","Export note (.md)","Drawing pad","Backlinks","Save as template","Delete"};new AlertDialog.Builder(this).setTitle("Note tools").setItems(items,(d,w)->{switch(w){case 0:chooseMode();break;case 1:chooseCommand(false);break;case 2:new AlertDialog.Builder(this).setTitle("Quick summary").setMessage(SmartTools.quickSummary(body.getText().toString())).setPositiveButton("OK",null).show();break;case 3:showActions();break;case 4:showRelated();break;case 5:save(false);startActivity(new Intent(this,HistoryActivity.class).putExtra("note_id",note.id));break;case 6:addTag();break;case 7:moveFolder();break;case 8:setReminder();break;case 9:setTime("unlock");break;case 10:setTime("expiry");break;case 11:toggleLock();break;case 12:chooseTheme();break;case 13:toggleFocus();break;case 14:voice();break;case 15:pickImage();break;case 16:camera();break;case 17:showAttachments();break;case 18:exportNote();break;case 19:save(false);startActivity(new Intent(this,DrawingActivity.class).putExtra("note_id",note.id));break;case 20:showBacklinks();break;case 21:saveTemplate();break;case 22:repo.trash(note.id);finish();break;}}).show();}
    private void maybeSlashCommand(){if(commandOpen||body==null)return;String s=body.getText().toString();if(s.endsWith("/")&&(s.length()==1||s.charAt(s.length()-2)=='\n'||Character.isWhitespace(s.charAt(s.length()-2))))chooseCommand(true);}
    private void chooseCommand(boolean removeSlash){if(commandOpen)return;commandOpen=true;String[]c={"check","date","time","heading","divider","quote","link"};AlertDialog dialog=new AlertDialog.Builder(this).setTitle("Command").setItems(c,(d,w)->{String current=body.getText().toString();if(removeSlash&&current.endsWith("/"))current=current.substring(0,current.length()-1);body.setText(CommandEngine.apply(c[w],current,System.currentTimeMillis()));body.setSelection(body.length());}).setNegativeButton("Cancel",null).create();dialog.setOnDismissListener(d->commandOpen=false);dialog.show();}
    private void chooseMode(){String[]m={"text","checklist","meeting","journal","shopping"};new AlertDialog.Builder(this).setTitle("Note mode").setItems(m,(d,w)->{note.mode=m[w];if(w>1&&body.getText().toString().trim().isEmpty()){String seed=w==2?"Date:\nPeople:\nTopic:\n\nKey Points:\n• \n\nAction Items:\n☐ ":w==3?"Today I feel…\n\nWhat happened:\n\nGrateful for:\n":"☐ ";body.setText(seed);}}).show();}
    private void showActions(){List<String>a=SmartTools.actionItems(body.getText().toString());new AlertDialog.Builder(this).setTitle("Action items").setMessage(a.isEmpty()?"No explicit TODO/action items found.":android.text.TextUtils.join("\n",a)).setPositiveButton("OK",null).show();}
    private void showRelated(){List<Note> candidates=repo.list("","all");List<Note> scored=new ArrayList<>();for(Note n:candidates)if(n.id!=note.id&&!n.locked&&SmartTools.relatedScore(note.title,body.getText().toString(),n.title,n.body)>0)scored.add(n);Collections.sort(scored,(a,b)->Integer.compare(SmartTools.relatedScore(note.title,body.getText().toString(),b.title,b.body),SmartTools.relatedScore(note.title,body.getText().toString(),a.title,a.body)));StringBuilder s=new StringBuilder();for(int i=0;i<Math.min(5,scored.size());i++)s.append("• ").append(scored.get(i).displayTitle()).append("\n");new AlertDialog.Builder(this).setTitle("Related notes").setMessage(s.length()==0?"No strong local matches yet":s.toString()).setPositiveButton("OK",null).show();}
    private void addTag(){EditText x=new EditText(this);x.setHint("Tag");new AlertDialog.Builder(this).setTitle("Add tag").setView(x).setPositiveButton("Add",(d,w)->{save(false);repo.addTag(note.id,x.getText().toString());}).setNegativeButton("Cancel",null).show();}
    private void moveFolder(){List<String>rows=repo.folderRows();String[]names=new String[rows.size()+1];names[0]="Root";for(int i=0;i<rows.size();i++){String[]p=rows.get(i).split("\\|",3);names[i+1]=p.length>1?p[1]:rows.get(i);}new AlertDialog.Builder(this).setTitle("Move to folder").setItems(names,(d,w)->{if(w==0)repo.moveToFolder(note.id,null);else repo.moveToFolder(note.id,Long.parseLong(rows.get(w-1).split("\\|",2)[0]));}).show();}
    private void setReminder(){if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},900);EditText x=new EditText(this);x.setHint("Minutes from now");x.setInputType(2);new AlertDialog.Builder(this).setTitle("Reminder").setView(x).setPositiveButton("Set",(d,w)->{try{long t=System.currentTimeMillis()+Long.parseLong(x.getText().toString())*60000L;save(false);repo.setReminder(note.id,t);ReminderScheduler.schedule(this,note.id,t);Toast.makeText(this,"Reminder set",Toast.LENGTH_SHORT).show();}catch(Exception e){Toast.makeText(this,"Enter a valid number",Toast.LENGTH_SHORT).show();}}).setNeutralButton("Clear",(d,w)->{repo.setReminder(note.id,0);ReminderScheduler.cancel(this,note.id);}).show();}
    private void setTime(String type){EditText x=new EditText(this);x.setHint("Minutes from now (0 clears)");x.setInputType(2);new AlertDialog.Builder(this).setTitle(type.equals("unlock")?"Time capsule":"Expiring note").setView(x).setPositiveButton("Save",(d,w)->{try{long min=Long.parseLong(x.getText().toString());long t=min<=0?0:System.currentTimeMillis()+min*60000L;if(type.equals("unlock"))note.unlockAt=t;else note.expiresAt=t;scheduleSave();}catch(Exception ignored){}}).show();}
    private void toggleLock(){if(!AppLock.hasPin(this)){Toast.makeText(this,"Set a PIN in Settings first",Toast.LENGTH_LONG).show();return;}note.locked=!note.locked;if(note.locked)unlocked=true;Toast.makeText(this,note.locked?"Note will be encrypted on save":"Note unlocked",Toast.LENGTH_SHORT).show();scheduleSave();}
    private void chooseTheme(){String[]t={"system","paper","dark","warm","contrast"};new AlertDialog.Builder(this).setTitle("Theme").setItems(t,(d,w)->{note.themeKey=t[w];applyTheme();scheduleSave();}).show();}
    private void applyTheme(){if(body==null)return;body.setTextColor(0xff202020);title.setTextColor(0xff202020);body.setBackgroundColor(0xffffffff);title.setBackgroundColor(0xffffffff);String t=note.themeKey==null?"system":note.themeKey;if(t.equals("dark")){body.setBackgroundColor(0xff171717);body.setTextColor(0xffeeeeee);title.setBackgroundColor(0xff171717);title.setTextColor(0xffffffff);}else if(t.equals("warm")){body.setBackgroundColor(0xfffff3df);title.setBackgroundColor(0xfffff3df);}else if(t.equals("contrast")){body.setBackgroundColor(0xff000000);body.setTextColor(0xffffffff);title.setBackgroundColor(0xff000000);title.setTextColor(0xffffffff);}else if(t.equals("paper")){body.setBackgroundColor(0xfffffdf7);title.setBackgroundColor(0xfffffdf7);}}
    private void toggleFocus(){focus=!focus;title.setVisibility(focus?View.GONE:View.VISIBLE);state.setVisibility(focus?View.GONE:View.VISIBLE);Toast.makeText(this,focus?"Focus mode on":"Focus mode off",Toast.LENGTH_SHORT).show();}
    private void voice(){try{Intent i=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);i.putExtra(RecognizerIntent.EXTRA_PROMPT,"Speak your note");startActivityForResult(i,VOICE);}catch(Exception e){Toast.makeText(this,"Speech recognition is not available on this device",Toast.LENGTH_LONG).show();}}
    private void pickImage(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("image/*").addCategory(Intent.CATEGORY_OPENABLE).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);startActivityForResult(i,IMAGE);}
    private void camera(){try{startActivityForResult(new Intent(MediaStore.ACTION_IMAGE_CAPTURE),CAMERA);}catch(Exception e){Toast.makeText(this,"No camera app available",Toast.LENGTH_LONG).show();}}
    private void showAttachments(){save(false);List<String>a=repo.attachments(note.id);new AlertDialog.Builder(this).setTitle("Attachments").setMessage(a.isEmpty()?"No attachments":android.text.TextUtils.join("\n",a)).setPositiveButton("OK",null).show();}
    private void exportNote(){save(false);Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT).setType("text/markdown").putExtra(Intent.EXTRA_TITLE,(note.displayTitle().replaceAll("[^a-zA-Z0-9._ -]","_")+".md"));startActivityForResult(i,EXPORT_NOTE);}
    private void showBacklinks(){List<Note>b=repo.backlinks(note.id);StringBuilder s=new StringBuilder();for(Note n:b)s.append("• ").append(n.displayTitle()).append("\n");new AlertDialog.Builder(this).setTitle("Backlinks").setMessage(s.length()==0?"No backlinks yet":s.toString()).setPositiveButton("OK",null).show();}
    private void saveTemplate(){EditText x=new EditText(this);x.setHint("Template name");new AlertDialog.Builder(this).setTitle("Save as template").setView(x).setPositiveButton("Save",(d,w)->{note.body=body.getText().toString();note.mode=note.mode==null?"text":note.mode;repo.saveAsTemplate(x.getText().toString(),note);}).setNegativeButton("Cancel",null).show();}
    @Override protected void onActivityResult(int requestCode,int resultCode,Intent data){super.onActivityResult(requestCode,resultCode,data);if(requestCode==DEVICE_UNLOCK){if(resultCode==RESULT_OK)decryptAndBuild();else finish();return;}if(resultCode!=RESULT_OK)return;try{if(requestCode==VOICE&&data!=null){ArrayList<String>r=data.getStringArrayListExtra(RecognizerIntent.EXTRA_RESULTS);if(r!=null&&!r.isEmpty())body.append((body.length()>0?"\n":"")+r.get(0));}else if(requestCode==IMAGE&&data!=null&&data.getData()!=null){getContentResolver().takePersistableUriPermission(data.getData(),Intent.FLAG_GRANT_READ_URI_PERMISSION);save(false);repo.addAttachment(note.id,"image",data.getData().toString());Toast.makeText(this,"Image attached",Toast.LENGTH_SHORT).show();}else if(requestCode==CAMERA&&data!=null&&data.getExtras()!=null){Object o=data.getExtras().get("data");if(o instanceof Bitmap){save(false);File dir=new File(getFilesDir(),"images");dir.mkdirs();File f=new File(dir,"camera-"+System.currentTimeMillis()+".png");try(FileOutputStream out=new FileOutputStream(f)){((Bitmap)o).compress(Bitmap.CompressFormat.PNG,95,out);}repo.addAttachment(note.id,"image",f.getAbsolutePath());Toast.makeText(this,"Camera image attached",Toast.LENGTH_SHORT).show();}}else if(requestCode==EXPORT_NOTE&&data!=null&&data.getData()!=null){try(OutputStream out=getContentResolver().openOutputStream(data.getData())){String md="# "+note.displayTitle()+"\n\n"+body.getText().toString();out.write(md.getBytes(StandardCharsets.UTF_8));}Toast.makeText(this,"Note exported",Toast.LENGTH_SHORT).show();}}catch(Exception e){Toast.makeText(this,"Operation failed: "+e.getMessage(),Toast.LENGTH_LONG).show();}}
    @Override protected void onPause(){if(title!=null)save(false);super.onPause();}
    @Override public void onBackPressed(){if(title!=null)save(false);super.onBackPressed();}
    private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
}
